// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Row
	QueryRequest
	QueryResponse
	ExecRequest
	ExecResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Row struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto1.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Row) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// The query statement
type QueryRequest struct {
	Stmt string `protobuf:"bytes,1,opt,name=stmt" json:"stmt,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto1.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryRequest) GetStmt() string {
	if m != nil {
		return m.Stmt
	}
	return ""
}

// The query response
type QueryResponse struct {
	Columns []string `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	Rows    []*Row   `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto1.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryResponse) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *QueryResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

// The exec statement
type ExecRequest struct {
	Stmt string `protobuf:"bytes,1,opt,name=stmt" json:"stmt,omitempty"`
}

func (m *ExecRequest) Reset()                    { *m = ExecRequest{} }
func (m *ExecRequest) String() string            { return proto1.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()               {}
func (*ExecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ExecRequest) GetStmt() string {
	if m != nil {
		return m.Stmt
	}
	return ""
}

// The exec response
type ExecResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ExecResponse) Reset()                    { *m = ExecResponse{} }
func (m *ExecResponse) String() string            { return proto1.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()               {}
func (*ExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExecResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*Row)(nil), "proto.Row")
	proto1.RegisterType((*QueryRequest)(nil), "proto.QueryRequest")
	proto1.RegisterType((*QueryResponse)(nil), "proto.QueryResponse")
	proto1.RegisterType((*ExecRequest)(nil), "proto.ExecRequest")
	proto1.RegisterType((*ExecResponse)(nil), "proto.ExecResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DBProvider service

type DBProviderClient interface {
	// Query executes a statement that reads data.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Exec executes a statement that writes data.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type dBProviderClient struct {
	cc *grpc.ClientConn
}

func NewDBProviderClient(cc *grpc.ClientConn) DBProviderClient {
	return &dBProviderClient{cc}
}

func (c *dBProviderClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/proto.DBProvider/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProviderClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := grpc.Invoke(ctx, "/proto.DBProvider/Exec", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DBProvider service

type DBProviderServer interface {
	// Query executes a statement that reads data.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Exec executes a statement that writes data.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
}

func RegisterDBProviderServer(s *grpc.Server, srv DBProviderServer) {
	s.RegisterService(&_DBProvider_serviceDesc, srv)
}

func _DBProvider_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DBProvider/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProvider_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DBProvider/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DBProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DBProvider",
	HandlerType: (*DBProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _DBProvider_Query_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _DBProvider_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto1.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x41, 0x4f, 0x02, 0x31,
	0x10, 0x85, 0xdd, 0xec, 0x82, 0x61, 0x80, 0xcb, 0x60, 0x4c, 0x43, 0xa2, 0x59, 0x7b, 0xea, 0x89,
	0x44, 0xf4, 0x17, 0x18, 0x3d, 0x78, 0xd3, 0xfe, 0x03, 0x5c, 0x27, 0x86, 0x84, 0x65, 0xb0, 0xd3,
	0xee, 0xea, 0xbf, 0x37, 0x76, 0xdb, 0x08, 0x17, 0x4f, 0xed, 0x7b, 0x7d, 0x9d, 0xef, 0x0d, 0xcc,
	0x85, 0x5c, 0xb7, 0x6d, 0x68, 0x75, 0x70, 0xec, 0x19, 0x47, 0xf1, 0xd0, 0x57, 0x50, 0x5a, 0xee,
	0xf1, 0x12, 0xc6, 0xdd, 0x66, 0x17, 0x48, 0x54, 0x51, 0x97, 0x66, 0x62, 0x93, 0xd2, 0x1a, 0x66,
	0xaf, 0x81, 0xdc, 0xb7, 0xa5, 0xcf, 0x40, 0xe2, 0x11, 0xa1, 0x12, 0xdf, 0x7a, 0x55, 0xd4, 0x85,
	0x99, 0xd8, 0x78, 0xd7, 0xcf, 0x30, 0x4f, 0x19, 0x39, 0xf0, 0x5e, 0x08, 0x15, 0x9c, 0x37, 0xbc,
	0x0b, 0xed, 0x3e, 0x4f, 0xcb, 0x12, 0xaf, 0xa1, 0x72, 0xdc, 0x8b, 0x2a, 0xeb, 0xd2, 0x4c, 0xd7,
	0x30, 0x54, 0x59, 0x59, 0xee, 0x6d, 0xf4, 0xf5, 0x0d, 0x4c, 0x9f, 0xbe, 0xa8, 0xf9, 0x8f, 0x66,
	0x60, 0x36, 0x44, 0xfe, 0x60, 0x2d, 0x89, 0x6c, 0x3e, 0x28, 0xc5, 0xb2, 0x5c, 0x07, 0x80, 0xc7,
	0x87, 0x17, 0xc7, 0xdd, 0xf6, 0x9d, 0x1c, 0xde, 0xc3, 0x28, 0xb6, 0xc4, 0x45, 0xa2, 0x1e, 0xef,
	0xb5, 0xbc, 0x38, 0x35, 0x87, 0xd9, 0xfa, 0x0c, 0x6f, 0xa1, 0xfa, 0xa5, 0x21, 0xa6, 0xf7, 0xa3,
	0x76, 0xcb, 0xc5, 0x89, 0x97, 0xbf, 0xbc, 0x8d, 0xa3, 0x7b, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x35, 0x92, 0xc1, 0x2b, 0x70, 0x01, 0x00, 0x00,
}
